### ISSUE TITLE
Razor `@model` doesn't work for nested layout with base model type

### ISSUE THREAD

**Issue by Crisfole** [NancyFx/Nancy#1974] opened 2015-06-30 17:20 UTC
Currently the best I can do is give an example. I have a core layout:

```
<header>Header</header>
<div id='wrapper'>@RenderBody()</div>
```
A subarea of the site with a layout inside:
```
@model MyInterfaceOrAbstractModel
@{ Layout = "layout" }
<section>Sub Section</section>
@RenderBody()
```
And a bunch of cshtml files that use the sub layout. Unfortunately it doesn't work. I get a `System.NotSupportedException` with the following error message:

    "Unable to discover CLR Type for model by the name of MyInterfaceOrAbstractModel"

At first I thought, oh my razor config must be wrong, but I proved that wrong because it works beautifully if I swap it out for an `@inherits` like so:
```
@inherits NancyRazorViewBase<MyInterfaceOrAbstractModel>
@{ Layout = "layout" }
<section>Sub Section</section>
@RenderBody()
```

Is this a Razor fact of life, or a bug in Nancy's razor support?

**Comment by phillip-haydon** [comment] 2015-07-01 01:54
I haven't tried with specific types, but it works fine for `dynamic`

**Comment by Crisfole** [comment] 2015-07-01 11:54
Yeah, I have a workaround. I just wasn't sure if this was a bug.

**Comment by phillip-haydon** [comment] 2015-08-22 12:50
This is because you need to include all the Razor Config for where your models are. 

https://github.com/NancyFx/Nancy/wiki/Razor-View-Engine#configuring-razor

Was just testing it now, reproduced, added config, error goes away. Using 4 layouts deep.

**Comment by phillip-haydon** [comment] 2015-08-22 12:50
Closing issue for now.

**Closed by phillip-haydon** 2015-08-22 12:50 UTC
