### ISSUE TITLE
Unable to get Self-Hosting to work in fresh project

### ISSUE THREAD

**Issue by c0bra** [NancyFx/Nancy#2046] opened 2015-08-31 18:45 UTC
After several hours of debugging I've hit a wall trying to get Self-hosting to work in a console app project.

Here's how I've tried setting it up:

1. Using "http://localhost:8888/" as the Uri (also have tried other port numbers)
2. Using "http://localhost:8888/test/" as the Uri so there's a path on it
2. Tried turning  Rewritelocalhost on and off
3. Tried setting UrlReservations.CreateAutomatically to true, with the above setting off.
4. Tried various frameworks 4.5.2, 4.5, 4.0
5. Tried this on multiple machines, in VS 2012, 2013, and 2015.

Here's what I've found:

1. No matter what I am unable to connect to the host. I invariable get connection refused, with no errors or exceptions and no debugging information.  I tried adding a BeforeRequest handler just in case but no luck.

Additionally, the Nancy.Hosting.Self demo project fails to run due to the need to reserve the namespace as per: https://github.com/NancyFx/Nancy/wiki/Self-Hosting-Nancy

Anyone have any tips at all?

**Comment by khellang** [comment] 2015-08-31 19:01
Tried running as admin?

**Comment by c0bra** [comment] 2015-08-31 20:03
Yep.

**Comment by khellang** [comment] 2015-08-31 20:58
This is super weird. It's definitely something with your machine/environment. I just set up a self-hosted console app in 2 min...

**Comment by damianh** [comment] 2015-09-01 10:09
@c0bra post your attempt to git hub so we can attempt to reproduce.

**Comment by phillip-haydon** [comment] 2015-09-27 14:30
Ahhh @c0bra - it might be easier to just use the Owin Self Host instead of the Nancy Self Hosting. Chances are you will have far fewer issues. 

In any case this thread looks like it's dead now so I'll close it until further notice.

**Closed by phillip-haydon** 2015-09-27 14:30 UTC

**Comment by uugan** [comment] 2018-12-27 13:59
Closed? how?

**Comment by cloudhunter89** [comment] 2018-12-27 16:21
Because connection refused is not something self-hosting does and they felt
there wasn't any responses coming from the op.  Have you run into a similar
problem?

**Comment by c0bra** [comment] 2018-12-27 16:52
Sorry, I got a new job and stopped using Nancy a little bit after this.
