### ISSUE TITLE
OnError pipeline exception is innermost exception

### ISSUE THREAD

**Issue by ekelundh** [NancyFx/Nancy#2077] opened 2015-10-20 15:25 UTC
For my error handling, I have defined a global exception handler that catches exceptions on the on error handling. As of version 1.3 - any exceptions with an inner exception (no matter how many inner exceptions) are only sent through the pipeline as the innermost exception. 

Is this expected behavior?

**Comment by khellang** [comment] 2015-10-20 17:54
This sounds like a dupe of #1638

**Closed by khellang** 2015-10-20 17:54 UTC
