### ISSUE TITLE
Unable to cast object of type 'DefaultStatusCodeHandlerResult' to Model type

### ISSUE THREAD

**Issue by xori** [NancyFx/Nancy#2122] opened 2015-11-20 21:28 UTC
This is a very weird bug that I've come across, and the most frustrating part is that 30% of the time it doesn't come up.

#### The Error
```
Server Error in '/' Application.
Unable to cast object of type 'DefaultStatusCodeHandlerResult' to type 'My.ModelType'.

[InvalidCastException: Unable to cast object of type 'DefaultStatusCodeHandlerResult' to type 'My.ModelType'.]
   Nancy.ViewEngines.Razor.NancyRazorViewBase`1.Initialize(RazorViewEngine engine, IRenderContext renderContext, Object model) +50
...
```

#### The Module
```c#
Get["/{transaction}"] = param => {
    var model = new EFDatabase().Transactions.Single(param.transaction);
    return Negotiate
        .WithView("Purchase")
        .WithModel(model); // I have confirmed this is not null
};
```

#### The View
```c#
@inherits Nancy.ViewEngines.Razor.NancyRazorViewBase<My.ModelType>
...
```

If I request the route `/transaction-id.json` I correctly get the JSON encoded string. But if I view the the route in the browser I get the ASP Error page (not the cute Nancy one) with the message listed above. Plus, the mentioned type `DefaultStatusCodeHandlerResult` is a Nancy error model to my understanding which leads me to believe that an error occurs (somewhere) and it tries to coerce that error to my specified View, rather than redirecting to the Nancy error page.

So my question is why am I getting this ASP error page, compared to a Nancy Error page? And what steps can I do to debug this? Google doesn't really have an answer to this `DefaultStatusCodeHandlerResult`

**Comment by jonathanfoster** [comment] 2015-11-21 03:40
The `DefaultStatusCodeHandlerResult` has to do with content negotiation in the default error handler. When requesting `text/html` the default error handler logic assumes there's no view for `DefaultStatusCodeHandlerResult` and renders the Nancy error page. There must be something in your project that's causing a view to be associated with the default error handler result. Is there anyway you could send me a sample project to repro this issue?

**Comment by xori** [comment] 2015-11-23 00:45
Unfortunately it's a very large project and hard to reproduce, but I will continue trying to create a reproducible example. 

The main difficulty is that sometimes it works (race condition?). Maybe with Entity Framework resolving the object proxy (the first time, failing) then it pulling from the cache correctly the second? 

Is there any way of inserting a handler into the pipe so that I can inspect that `DefaultStatusCodeHandlerResult` object and see the `Message` it holds?

**Comment by khellang** [comment] 2015-11-23 01:06
Because you're specifying a view and a model, using `return Negotiate.WithView("Purchase").WithModel(model);` and the `DefaultStatusCodeHandler` just [passes on the `NancyContext` to the `IResponseNegotiator`](https://github.com/NancyFx/Nancy/blob/06cf21609b5e61bee5b16e0b1f21e9341635a785/src/Nancy/ErrorHandling/DefaultStatusCodeHandler.cs#L77) without resetting the `NegotiationContext`, it'll [try to render the view specified](https://github.com/NancyFx/Nancy/blob/06cf21609b5e61bee5b16e0b1f21e9341635a785/src/Nancy/Responses/Negotiation/ViewProcessor.cs#L60), using the model specified. Since the view has `@inherits Nancy.ViewEngines.Razor.NancyRazorViewBase<My.ModelType>`, the cast fails. This will only happen if you request `text/html`, i.e. from a browser.

**Comment by khellang** [comment] 2015-11-23 01:07
I can look into this if @jonathanfoster isn't into it. It's probably just a matter of making sure the `NegotiationContext` is in a good state before passing it to the negotiator.

**Comment by xori** [comment] 2015-11-23 15:59
Yup, I'm now positive that this has something to do with how Nancy deals with EF's proxy classes.

With a view that consists of *only*
```C#
@inherits Nancy.ViewEngines.Razor.NancyRazorViewBase<My.Type>
```
and the simple Module listed above I get my reported error on the **first** page load, on subsequent loads it works. But if I compile again it will error the first page hit.

If I replace the above Module with this one
```C#
Get["/{transaction}"] = param => {
    return Negotiate
        .WithView("Purchase")
        .WithModel(new My.Type());
};
```
It works.

**Comment by xori** [comment] 2015-11-23 16:16
By using http://stackoverflow.com/a/25774651 I was able to get it to work consistently. However I don't feel confident using this in production so I'll greatly appreciate it when this issue does get fixed.

**Comment by jonathanfoster** [comment] 2015-11-24 03:35
It looks like the invalid cast is occurring in the `NancyRazorViewBase` constructor. @xori, as a work around you should be able to use ```

**Comment by jonathanfoster** [comment] 2015-11-24 03:44
@khellang, it looks like the invalid cast is occurring in the `NancyRazorViewBase` constructor. I'm able to resolve the issue by nulling out the view name in the negotiation context. Would it be better to simply create a new `NegotiationContext` in the event of an error? This would avoid any other potential negotiation context issues.

**Comment by tofutim** [comment] 2015-12-03 04:36
I ran into this today.

**Comment by tofutim** [comment] 2015-12-03 07:02
I feel like this is new, as my code used to work.

**Comment by tofutim** [comment] 2015-12-03 07:13
This seems to be a problem when the number of results is large. when it is small i do not see the issue. Maybe a timing issue for EF?

**Comment by thecodejunkie** [comment] 2015-12-03 07:27
We're pretty much going to need a reliable reproduction of this. Either as a minimal viable application or as failing unit tests. If either of you guys can help us by suppling either, then we can start looking into this. 

Thanks

**Comment by thecodejunkie** [comment] 2015-12-03 07:30
> This seems to be a problem when the number of results is large. when it is small i do not see the issue. Maybe a timing issue for EF?

Bit curious if this is related to the [MaxJsonLength](https://github.com/NancyFx/Nancy/blob/v1.4.2/src/Nancy/Json/JsonSettings.cs#L34) of the JSON response being hit. This isn't something new, but it would explain the above theory

**Comment by tofutim** [comment] 2015-12-03 07:45
No, I just figured it out, I had a cshtml that was referring to an item in
my results which was null and trying to pull a property off of it. Strange
error but that was the problem.

On Wed, Dec 2, 2015 at 11:30 PM, Andreas Håkansson <notifications@github.com

**Comment by grumpydev** [comment] 2015-12-03 07:47
If you could put together a repro project so we can make the error more meaningful that would be great.

**Comment by tofutim** [comment] 2015-12-03 08:30
Let me see what I can do.

**Comment by tofutim** [comment] 2015-12-03 10:01
Try this

https://github.com/tofutim/UnableToCastDefaultStatusCodeHandlerResult

**Comment by tofutim** [comment] 2015-12-03 10:03
I need the error to tell me that I have a NullReferenceException in the
razor - but maybe this is too much to ask. The current error though is
really cryptic. In my real example, the model was a dynamic EF result so I
spent a long time trying ToList() AsEnumerable, etc. when really I was just
calling a property from a property that happened to be null in the cshtml
(forgot an if null on one of my fields).

**Comment by jonathanfoster** [comment] 2015-12-03 16:32
I submitted PR https://github.com/NancyFx/Nancy/pull/2140 to resolve this issue. You can reproduce it in https://github.com/jonathanfoster/nancy-demo-errorhandlerinvalidcastexception/.

**Comment by khellang** [comment] 2015-12-03 22:13
Closed by #2140. It would be nice if someone pulled a CI build off MyGet and verified the fix :smile:

**Closed by khellang** 2015-12-03 22:13 UTC
Labels: Bug

**Comment by kylebjones** [comment] 2015-12-09 17:09
Hello,

I just started working with Nancy and I am getting this error every time I bind a model to my views, doesn't matter the size.  Any idea when this fix will be pushed out to a new Nuget package?  I am currently running the latest 1.4.2.

Thanks

**Comment by khellang** [comment] 2015-12-21 12:11
Version 1.4.3 was just pushed to [NuGet](https://www.nuget.org/packages/Nancy/1.4.3).
