### ISSUE TITLE
relative paths with query parameters are not working as expected with Nancy.Testing.Browser

### ISSUE THREAD

**Issue by fschwiet** [NancyFx/Nancy#2192] opened 2016-01-17 05:54 UTC
I ran into a related SO thread trying to pass query parameters directly from a HREF value to new Browser(): http://stackoverflow.com/questions/10718763/nancyfx-routes-with-query-string-parameters-always-returns-a-404-notfound.

  Its claimed these tests pass: https://gist.github.com/thecodejunkie/204297b492e1ab5b3e2f
  However, this test fails with InvalidUriException:

        public void Should_return_querystring_parameter_when_passed_in_with_path()
        {
            // Given
            var url = new Url("/?foo=bar3");

            // When
            var result = this.browser.Get(url);

            // Then
            Assert.Equal("bar3", result.Body.AsString());
        }

  It is interesting to note that the gist tests are missing the [Fact] attribute.  So maybe this test was never run?

**Comment by thecodejunkie** [comment] 2016-01-17 21:36
I just run the tests (added the missing `[Fact]` attributes first) and they works just fine

![image](https://cloud.githubusercontent.com/assets/50543/12380112/6ca6ae98-bd6a-11e5-9e3b-9baa6e5184fe.png)

The only thing I've done is make them do an `async` call because I tested this in the code that will be part of `v2.0`, but no changes have been made to route parsing for the `Browser`

![image](https://cloud.githubusercontent.com/assets/50543/12380106/6485b164-bd6a-11e5-8b6d-7309189e6d4d.png)

We're going to need executable code that shows this happening or we can't look closer at it because we cannot even reproduce it :D

**Comment by fschwiet** [comment] 2016-01-21 06:33
Can I have a link to the test or test project?  I wonder if I am pulling in a different namespace or assembly and am getting a different Url class.

**Comment by fschwiet** [comment] 2016-01-21 06:57
The issue is that new Nancy.Url("/path") throws an exception.  The exception is coming from System.Uri, so maybe the version of the .NET runtime matters.  The exception I see from Nancy.Url is:

    Unhandled Exception: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
       at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
       at System.Uri..ctor(String uriString)
       at Nancy.Url..ctor(String url)
       at ReproNancyUrlIssue.Program.Main(String[] args) in c:\code\ReproNancyUrlIssue\ReproNancyUrlIssue\Program.cs:line 13


  which can be repro'd here: https://github.com/fschwiet/Nancy2192

  As a workaround, I add "http://localhost" to the front of all relative urls in my tests.  The impact is minor, it just feels a little less super to specify a (hopefully) unused hostname.

**Comment by fschwiet** [comment] 2016-01-21 07:06
When the path doesn't have a querystirng there is no problem passing it direclty.  My example didn't include a querystring when showing the exception, but it behaves.  The problem with the test API is only when I have a path+querystring.

**Comment by vzakanj** [comment] 2016-02-11 10:19
Having a similar issue, not sure if it's completely related so let me know if I should open another github issue.

I've used the following test code to reproduce this:

Module
```
public class RelativePathQueryStringModule : NancyModule
{
	public RelativePathQueryStringModule()
	{
		Get["/test"] = _ =>
		{
			return this.Request.Query["foo"];
		};
	}
}
```

Browser test code:
```
var browser = new Browser(with => with.Module<RelativePathQueryStringModule>());
	
var rsp = browser.Get("/test?foo=bar");
Asserts.Equal("bar", rsp.Body.AsString());
```

The assertion fails when the Get method is called with a relative URL containing a query string (as in the example), but if change the URL to an absolute one ("http://localhost/test?foo=bar") everything works as expected.

I'm using the following packages from the official nuget source:
Nancy - 1.4.3
Nancy.Testing - 1.4.1

**Comment by grumpydev** [comment] 2016-02-11 11:01
Use the "with.Query" builder method, putting the querystring straight into the url in the Get parameter isn't something we support.

**Closed by grumpydev** 2016-02-11 11:01 UTC
