### ISSUE TITLE
Garbage added to multipart-formdata running selfhost on mono

### ISSUE THREAD

**Issue by umby24** [NancyFx/Nancy#1865] opened 2015-03-12 16:41 UTC
I am running a Nancy self host, using v1.10.0 from NuGet in my project. Everything runs fine under Windows with .NET 4.5, however issues arise when submitting larger files (~ 9 MB) to the nancy self host on mono.

The files become corrupted by Nancy when running in Mono. This is evidenced by several things. First is a wireshark capture running on the linux machine that is able to carve the submitted file successfully with no corruption.

Next is that the HTTP Headers content length field is of different size than the http body, because null bytes become added to the http body for some reason.

The corruption always seems to occur at the same place in the file, and is always null bytes (0x00)

This is example code for that should show the issue, when sending a ~9 MB file.

```C#
Post["/fileupload"] = x => {
                var myFile = Request.Files.FirstOrDefault();
                byte[] data;

                if (myFile != null) {
                    data = new byte[myFile.Value.Length];
                    Log(LogType.Debug, "Body Length: " + data.Length);
                    Log(LogType.Debug, myFile.Value.Read(data, 0, data.Length).ToString());

                    using (var fs = new FileStream("out.zip", FileMode.Create)) {
                        myFile.Value.CopyTo(fs);
                    }
                }
                else {
                    Log(LogType.Debug, "File is null.. " + Request.Headers.ContentLength);
                    Log(LogType.Debug, "Info: " + Request.Body.Length + " " + Request.Headers.ContentType);
                    data = new byte[Request.Headers.ContentLength];
                    Request.Body.Read(data, 0, data.Length);
                }
}
```

The else statement is always taken (File is null), if that information helps.

**Comment by starock** [comment] 2015-04-21 14:57
Me too...

**Comment by cvetomirtodorov** [comment] 2015-04-22 19:52
Occurs in Nancy 1.2 too with Mono 3.12.1 on Ubuntu 14.04.

**Comment by cvetomirtodorov** [comment] 2015-04-23 15:55
After debugging for a while I think the reason for the problem is explained in this bug I raised https://bugzilla.xamarin.com/show_bug.cgi?id=29337.

Problem is that I could not make things work without specifying `useAsync: false` when creating the `FileStream` in `RequestStream.CreateTemporaryFileStream` method. Looks like async operations on the `FileStream` in mono are not working well with large streams. One temporary solution would be to set `useAsync` to `false` when on mono, although that would degrade performance I suppose.

Also, I think the issue https://github.com/NancyFx/Nancy/issues/1796 is related to this one.

**Comment by cvetomirtodorov** [comment] 2015-04-27 20:08
Looks like the bug is fixed and will be released in mono 4.0 http://www.mono-project.com/docs/about-mono/releases/4.0.0/

**Comment by ChlorideCull** [comment] 2015-05-04 06:14
Can confirm that it's fixed in the stable Mono from upstream. Directions to add the Xamarin repository is [here](http://www.mono-project.com/docs/getting-started/install/linux/).

**Comment by khellang** [comment] 2015-05-04 08:14
Closing this for now then :smile:

**Closed by khellang** 2015-05-04 08:14 UTC
Labels: Bug, Up for Grabs
