### ISSUE TITLE
Nancy.Hosting.Self not serving static content from folders

### ISSUE THREAD

**Issue by slozier** [NancyFx/Nancy#1789] opened 2015-01-26 15:45 UTC
Serving static content from folders with AllowChunkedEncoding = true (which is the default) is failing.

To replicate you can use the Nancy.Demo.Hosting.Self app, stick any file in the Contents folder, try to navigate to that file.

My guess is SendChunked is not set on the HttpListenerResponse...

**Comment by beachwalker** [comment] 2015-01-26 21:06
I can reproduce this behaviour. I use a Selfhost app, too.

**Comment by dealproc** [comment] 2015-01-27 04:21
I went through something to this affect, and wound up using the `Microsoft Owin StaticFiles` middleware to get around issues.

My main reason was that I needed to serve a file called `RELEASES` with no extension, and Nancy seems to not have a capability of doing so.

HTH

**Comment by jdcrutchley** [comment] 2015-01-28 18:13
Can the Microsoft middleware be used with self-hosting?  I thought that was only for OWIN hosts.

**Comment by albertjan** [comment] 2015-01-28 18:53
#1788 fixes this I think

**Comment by jay-ho** [comment] 2015-01-29 16:55
I can reproduce this.  Self-hosted app, static items failing.  Same code worked fine before I blindly updated from 0.22.2 to 1.0.

**Comment by xivk** [comment] 2015-02-02 10:35
I'm having the same problem at the moment.

**Comment by joha1712** [comment] 2015-02-03 08:34
I'm having the same problem in a selfhosted windows service using Nancy. I'm not using OWIN/Katana, so it's a really selfhosted app. The browser can't view my static content (a css file) - and  I don't even get the Nancy 404 page. I just get "this page cannot be displayed" in chrome/IE.

When I set AllowChunkedEncoding = false in the HostConfiguration it works.
This took me 4 long hours to figure out, so I hope this issue will be fixed soon. So other users don´t wouldn´t have to go through the same frustrations...

**Comment by albertjan** [comment] 2015-02-03 08:42
it is fixed as of #1788

**Comment by beachwalker** [comment] 2015-02-04 21:38
Cool. Is there a release 1.0.1 on nuget.org planned containing this fix? Some kind of schedule?

**Comment by mawasak** [comment] 2015-02-08 16:16
Thanks for this workaround (AllowChunkedEncoding = false in the HostConfiguration) - this issue description save me from next few hours of digging. Thanks.

**Comment by flnielsen** [comment] 2015-02-10 11:17
Same issue for me

Nancy simply aborts the response/connection, even though the file is found and read from disk. If i do a GET /Content/test.html through telnet the file content is returned successfully  - maybe because the file is not chunked from the server.

Thanks for the fix.

**Comment by khellang** [comment] 2015-02-18 20:06
Can anyone verify that this works with 1.1 that was pushed today? Thanks! :smile:

**Closed by khellang** 2015-02-18 20:06 UTC
Labels: Bug

**Comment by chris-ray** [comment] 2015-02-18 20:32
I verify that this corrected the problem for me. Thanks!

**Comment by flnielsen** [comment] 2015-02-19 08:34
Confirmed, v1.1 solve the problem. 

Thanks

**Comment by khellang** [comment] 2015-02-19 08:57
Awesome, guys :metal

**Comment by ZloyZlobin** [comment] 2015-03-16 16:40
Thanks for AllowChunkedEncoding = false, it saved me a lot of time.
