### ISSUE TITLE
AbstractorValidator<> not found in external lib

### ISSUE THREAD

**Issue by jchannon** [NancyFx/Nancy#1287] opened 2013-10-24 08:55 UTC
Hopefully this is fixed by #1267 but if you have a Nancy app that references another lib that has a Person model and a PersonValidator and you call Validate in the module, it will not find the PersonValidator.  

Even using the ADAS in the Bootstrapper to load the assembly it still wont find it.  Move the PersonValidator to the web app and it finds it.

**Comment by janbaer** [comment] 2015-01-20 16:22
Is this problem fixed in the meantime? We're working with the latest release of NancyFX and we've the same problem. In our UnitTests **AppDomainAssemblyTypeScanner.AddAssembliesToScan** has helped but not in our productive bootstrapper. Is there any activity for this problem? Thanks!

**Comment by wtilton** [comment] 2015-02-23 18:37
I have two computers. Setup the second development environment today on the laptop and I'm running into this error. Exact same source,just pull it in from a git repo and yet one computer is having the issue and the other is not. Talk about completely strange? Is there not a fix for this anywhere? I'm using the default TInyIOC container NancyFx version 0.23.2.0. I suppose I could try upgrading to see if the problem is fixed although not sure why this issue would still be open.

**Comment by khellang** [comment] 2015-02-24 00:07
This is not a bug - in fact it's expected behavior. Correct me if I'm wrong, but I think Nancy's assembly loading and scanning should be covered in the documentation somewhere (I'm too lazy to check on my phone). If it isn't - here we go:

Nancy has this (already mentioned) infamous mechanism called the `AppDomainAssemblyTypeScanner` (ADATS) that will (by default) try to load all assemblies referencing Nancy.dll from the bin folder (since these will most likely contain Nancy services), then scan those assemblies for implementations/inheritors of well-known types. See `NancyInternalConfiguration` for default types. These types will typically be registered in the IoC container and instances resolved by services/modules that needs them at runtime. This plays a huge role in Nancys Super-Duper-Happy-Path (SDHP) and is why there's (in a majority of the cases) almost no configuration needed - it Just Works! It sounds to me, though, that you've come across a path where this default behavior is just not enough.

The problem you're describing can occur in two ways:
 1. The assembly that contains the validators is not referencing Nancy.dll.
 2. The assembly that contains the validators is not referenced (and used) either directly or indirectly by the main assembly/application, and thus not present in the bin folder.

The first problem can easily be fixed by using the method described above (`AddAssembliesToScan`).

The second problem could be a bit trickier (just because the compiler can be a bit too smart sometimes). This scenario typically happens if you either have an indirect assembly reference or the assembly consists only of types needed at runtime (discovered through reflection, using something like ADATS), e.g. there's no compile-time usage of any types in the assembly. Since the compiler sees that you don't use any types from it (at compile-time, at least), it will try to be smart and remove the reference, and the assembly will not be copied to build output, even though you've referenced the project in your main assembly/application. A solution to this is to make sure the reference is set to `CopyLocal: True` and that at least one type from the assembly is used somewhere.

**Closed** 2015-02-24 12:33 UTC

**Comment by janbaer** [comment] 2015-02-24 16:11
Sorry, we haven't known that the assembly that implements a validator via the FluentValidation must have also a reference to Nancy. Where is this documented? Maybe we haven't seen it. But we're using our Domain classes including their validators also in other of our applications. So therefore it wasn't our intention to reference the Webbframework Nancy in our business assemblies. But I'll try if the reference to Nancy helps. Thanks!

**Comment by khellang** [comment] 2015-02-24 19:04
@janbaer They don't *have to* reference Nancy, it's just the default way for Nancy to pick up assemblies that should be scanned for types. If you want to add other assemblies to the scanning process, you have to call the `AppDomainAssemblyTypeScanner.AddAssembliesToScan` method :smile:
