### ISSUE TITLE
Nancy testing Body.DeserializeJson<..> auto uppercases first character when deserialzing a dictionary

### ISSUE THREAD

**Issue by PureKrome** [NancyFx/Nancy#1868] opened 2015-03-13 10:30 UTC
Nancy.Testing allows us to test our results from a browser call. If the json result contains a dictionary (key/value) piece of data, it deserializes the json piece of data but _uppercases_ the first character of the **key** value in the key/value object.

For example.

given this json result...

```
{
  "message": "Something bad happened.",
  "errors": {
    "notificationId": "blah blah blah"
  }
}
```

and then this nancy testing code ...

`var modelWithBadKey = result.Body.DeserializeJson<FakeData>();`

this assert fails..

`modelWithBadKey.Errors.First().Key.ShouldBe("notificationId");`

the value is (incorrectly) set as `NotificationId`. <-- notice the upper case, first character?

Don't believe me: [I've made a _full_ repo](https://gist.github.com/PureKrome/7eed45a0f248b769675f) to prove it.

So, is this _by design_ ?

**Comment by khellang** [comment] 2015-03-13 10:36
@PureKrome Yes, this is by design. There's a property called `JsonSettings.RetainCasing` that'll allow you to control this. By default it's set to `false`, which means
 - Serialize: `NotificationId` -> `notificationId`
 - Deserialize: `notificationId` -> `NotificationId`

If you want to retain the original casing for JSON keys, flip it to `true` :smile:

**Comment by PureKrome** [comment] 2015-03-13 10:43
AH! gotcha! Also .. quick googling for `JsonSettings.RetainCasing` links to [this similar issue](https://github.com/NancyFx/Nancy/issues/1484).

So how do I set this value, for a Nancy.Test?

**Comment by khellang** [comment] 2015-03-13 10:56
In your setup?

**Comment by PureKrome** [comment] 2015-03-13 10:56
yep. figure it out :)

/me hugs u.

**Comment by khellang** [comment] 2015-03-13 11:00
Well, de-/serializing .NET dictionaries shouldn't affect the keys IMO, so it's still a bug. Glad you got it working :+1:

**Comment by PureKrome** [comment] 2015-03-13 11:03
But .. ok. now i'm confused :/

Your fix worked -> it _retained_ the casing during the _deserialization_. 

So are you saying that .. during _deserialization_ ... the key content should _not_ be altered at all and that `RetainCasing` value should _not_ be used at all during _deserialzation_ of dictionary keys? Because, right now .. it is.

**Comment by khellang** [comment] 2015-03-13 11:29
Yes, it shouldn't. And yes, right now it is. Hence why it's a bug :winK:

**Comment by PureKrome** [comment] 2015-03-13 11:38
Gotcha! ok - re-opening the issue and I'll let you guys deal with it, from here :+1:

**Comment by khellang** [comment] 2015-03-13 11:52
I think this is a dupe of #1484 then :smile:

**Closed by khellang** 2015-03-13 11:52 UTC
