### ISSUE TITLE
Can't register multiple instances of IDiagnosticProvider of same type

### ISSUE THREAD

**Issue by OZCMRDM** [NancyFx/Nancy#1830] opened 2015-02-23 22:26 UTC
IDiagnosticProviders gets registered as their type name, meaning only 1 can be registered. Should allow multiple instances, or allow IDiagnosticProvider to specify multiple diagnostic objects. 

Issue is due to this line:

DiagnosticModuleCatalog.ConfigureContainer

diagContainer.Register<IDiagnosticsProvider>(diagnosticsProvider, diagnosticsProvider.GetType().FullName)

**Comment by phillip-haydon** [comment] 2015-08-20 07:16
@OZCMRDM can we have some more information please. 

Can you link us to where this is being registered and what the scenario is you're experiencing. Something that helps us reproduce the problem you're having. 

I don't really understand the problem at the moment.

**Comment by thecodejunkie** [comment] 2015-08-20 07:56
Yes, do not quite understand the scenario where this would happen?

**Comment by thecodejunkie** [comment] 2015-08-20 08:52
Removing the `Bug` label from this and closing it for now. This is working as intended, i.e it is a design choice. Should you have more information to provide about this use case and why it should be changed, please post it here and we will re-evaluate it for a future release.

Thank you

**Closed by thecodejunkie** 2015-08-20 08:52 UTC

**Comment by OZCMRDM** [comment] 2015-08-20 11:59
I want 1 diagnostic provider instance per entity type/service that I have (i.e. a generic diagnostic provider). This doesn't work though since the provider registration is per type.

**Comment by thecodejunkie** [comment] 2015-08-20 12:01
@OZCMRDM please provide a bit of code that illustrates what you want to do. Thanks

**Comment by phillip-haydon** [comment] 2015-08-20 12:03
I assume that `IDiagnosticProvider` is your own interface? I don't believe Nancy has any such type? And you would like to register many different instances. 

Do they need to be named? Because you can register a collection of a specific type. 

If you need named dependencies then you will need to use a different IoC container with Nancy, like StructureMap.

**Comment by thecodejunkie** [comment] 2015-08-20 12:05
@phillip-haydon hehe c'mon [IDiagnosticsProvider](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Diagnostics/IDiagnosticsProvider.cs) :-D

**Comment by OZCMRDM** [comment] 2015-08-20 12:07
Something like this won't work (sorry forgot it isn't actually generic - but you see what I mean).

  class ServiceDiagnosticsProvider : IDiagnosticsProvider
    {
        public string Description
        {
            get { return null; }
        }

        public ServiceDiagnosticsProvider(object diagnosticObject)
        {
            DiagnosticObject = diagnosticObject;
        }

        public object DiagnosticObject
        {
            get;
            set;
        }

        public string Name
        {
            get { return DiagnosticObject.GetType().Name; }
        }
    }



Then I have something like this 

  public class NancyBootstrapper : AutofacNancyBootstrapper
    {
        private readonly IContainer _container;
        private readonly ILogger _logger;

        public NancyBootstrapper(IContainer container, ILogger logger)
        {
            if (container == null) throw new ArgumentNullException("container");
            if (logger == null) throw new ArgumentNullException("logger");
            _container = container;
            _logger = logger;
        }

        protected override ILifetimeScope GetApplicationContainer()
        {
            return _container;
        }

        protected override void ApplicationStartup(ILifetimeScope container, IPipelines pipelines)
        {
            base.ApplicationStartup(container, pipelines);

            ContainerBuilder cb = new ContainerBuilder();
            foreach (IEntityService ii in container.Resolve<IEnumerable<IEntityService>>())
            {
                ServiceDiagnosticsProvider sdp = new ServiceDiagnosticsProvider(ii);
                cb.RegisterInstance(sdp).As<IDiagnosticsProvider>();
            }
            cb.Update((IContainer)container);

**Comment by thecodejunkie** [comment] 2015-08-20 12:13
That was never their designed use case. All instances of `IDiagnosticsProvider` are automatically discovered and wired up. This is not something that we currently support. The correct way to move forward with this is to use a compound key like

```c#
var key = string.Concat(
   diagnosticsProvider.GetType().FullName,
   "_",
   diagnosticsProvider.DiagnosticsObject.GetType().FullName)
```

And use that as the key instead. That would solve your problem, correct (we would, of course, have to put that code into Nancy before it would work)

**Comment by OZCMRDM** [comment] 2015-08-20 12:20
Yes, that is a Nancy code change that would solve the issue.

**Comment by thecodejunkie** [comment] 2015-08-20 12:55
Sent a pull-request #2024 that will enable you to do this in v1.3
