### ISSUE TITLE
Model Binding - Deserialize both Body and params into a class

### ISSUE THREAD

**Issue by codri** [NancyFx/Nancy#2636] opened 2016-11-24 16:37 UTC
Based on the documentation page for Model binding

> Data can be sent to your Nancy application in many ways, for instance as part of the query string, as captured parameters on a route or as the body of a request. Manually working with the data spread out over several places is perfectly fine in some scenarios, but there are times where you want to unify that into something richer - a model - which is where Nancy’s “model binding” capabilities come into play.

I was under impression that is possible to combine the Request body and a Url param into one model.

Let's say, a call is coming with a param in the url `endpoint/{id}` and an XML payload:

```
<A>
   <Field>value</Field>
</A>
```

The helper class for deserializing the XML is next.
```
public class A
{
     public string Field;
}
```

Is it possible to make a model to extract these 2 from the request? For example having a model like this?

```c#
public Model
{
     public string id; // this is extracted from the URL
     public A body; // this is extracted from the body.
}
...

Post["endpoint/{id}"] = _ =>
{
    var model = this.Bind<Model>();
};

```

Does it make sense? Is it possible?

**Comment by jchannon** [comment] 2016-11-24 16:50
Should be possible. Have you found it doesn't work?

**Comment by codri** [comment] 2016-11-24 17:54
Yes. I think so. I get a XmlSerialization exception, at (1,1) when trying to bind on the Model.

```c#
var model = this.Bind<Model>();
```

And it successfully binds to the class that represents the XML body.

```c#
var body = this.Bind<A>();
```

**Comment by jchannon** [comment] 2016-11-25 16:38
I just noticed your issue.

You're using a Get not a Put or Post.

Change it to that and it should work

**Comment by codri** [comment] 2016-11-25 20:09
Unfortunately, Get was a typo in the example. The actual code uses a Post. Will try to debug Nancy if I'll have some time. As far as I understand the field name doesn't matter, be it 'Body', 'body' or 'A'. And the Model binding looks for the type.

**Comment by jchannon** [comment] 2016-11-25 20:26
I just tried this with json and worked as expected. Will see what XML does
```
            Post("/{id:int}", _ =>
            {
                var myclass = this.Bind<MyClass>();

                return myclass;
            });

           
    public class MyClass
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
```

`curl POST --data "{\"name\":\"fred\"}" -H "Content-Type:application/json" http://localhost:5000/123 -v`

**Comment by jchannon** [comment] 2016-11-25 20:30
Looks like we have a XML issue, this results in an exception

```
"   at Nancy.ModelBinding.DefaultBinder.Bind(NancyContext context, Type modelType, Object instance, BindingConfig configuration, String[] blackList)
   at Nancy.ModelBinding.DynamicModelBinderAdapter.TryConvert(ConvertBinder binder, Object& result)\n   at CallSite.Target(Closure , CallSite , Object )
   at netcorenancyapp.HomeModule.<.ctor>b__0_0(Object _) in /Users/jonathan/Projects/netcorenancyapp/myapp/HomeModule.cs:line 17
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.<Invoke>d__2.MoveNext()"
```

`curl POST --data "<xml><name>bob</name></xml>" -H "Content-Type:application/xml" http://localhost:5000/123 -v`

**Comment by codri** [comment] 2016-11-25 20:35
So this is a valid bug?

**Comment by jchannon** [comment] 2016-11-25 20:36
Looks like it. Ae you running on dotnetcore? That's where I see the issue

I guess this could be an issue with dotnetcore @NancyFx/most-valued-minions

**Comment by codri** [comment] 2016-11-25 20:38
No, I'm running in .NET 4.0, but I've also seen it in .NET 4.5, both on Windows.
Also, have you also tried `<name>bob</name>` for the XML payload?

**Comment by jchannon** [comment] 2016-11-25 20:38
What version of Nancy do you see this on?

**Comment by codri** [comment] 2016-11-25 20:43
I was using a really old one from Nuget, I think it was 0.2 or something.

But I've updated to the latest version from Nuget, 1.4 I think. And the issue persisted. In the old version, the exception thrown would be a naked XmlSerialization Exception, (1,1), which most likely means the Type it tries to deserialize with, doesn't match the XML.

In the latest Nancy, the exception is wrapped into a DataBindingException. So, I assume the issue has been here for a while.

**Comment by codri** [comment] 2016-11-25 20:47
Also, I think I've seen a similar issue when trying to deserialize the XML directly from the Request Body stream. Though, that's can be a false memory. Will investigate, and raise another issue, if it reproduces.

I've bypassed the Request Body Stream issue, by reading the Body stream into a String, then used a StringReader for deserialization. Didn't know about the Model binding at the time.

**Comment by jchannon** [comment] 2016-11-25 20:56
I'm not sure why it would exist in older packages especially 1.4 as we have a lot of tests around deserializing. There is a potential something in dotnetcore has changed though. Very odd

**Comment by codri** [comment] 2016-11-25 21:09
It's indeed a weird one, that's why I thought I was doing something wrong.

**Comment by thecodejunkie** [comment] 2016-11-25 23:28
No it's not a bug and it's not weird. The root element of the XML has to be the name of the model type + by default the XML serializer (`System.Xml.Serialization.XmlSerializer`) is also case sensitive (XML is inheritly case sensitive so there's no configuration to control this on `XmlSerializer` you have to resort to things like `IXmlSerializable` to control it) so you have to keep that in mind.

I just created the following model

```
public class Model
{
    public string Name { get; set; }
}
```

Posted the the following payload

```
POST http://localhost:53326/bind HTTP/1.1
User-Agent: Fiddler
Content-Type: application/xml
Host: localhost:53326
Content-Length: 35

<Model><Name>Andreas</Name></Model>
```

and it works great

![image](https://cloud.githubusercontent.com/assets/50543/20636524/d0b12436-b36e-11e6-9a35-6dbc4c6e0b66.png)

I'm going to close this issue. Please let me know if it still does not work for you and we can look at re-opening it

**Closed by thecodejunkie** 2016-11-25 23:28 UTC

**Comment by codri** [comment] 2016-11-26 06:45
@thecodejunkie I've mentioned in beginning that this scenario works for me as well.

> But it successfully binds to the class that represents the XML body.
`var body = this.Bind<A>();`

The issue appears when the Model also contains parts of the URL. And the body type as a field.

**Comment by thecodejunkie** [comment] 2016-11-26 10:44
@codri that won't work. How is the model binder supposed to know that part of your model would be a good candidate to bind the body, through XML serialization? The model binder works on the top level of the model class, not per property. I you want this sort of behavior then you need to write your own `IBinder` or do it in two steps. Bind `Model` and `MetaModel` separately and then combine the instances yourself.

**Comment by codri** [comment] 2016-11-26 15:17
I assumed it should work based on what's written in the documentation.

> Data can be sent to your Nancy application in many ways, for instance as part of the query string, as captured parameters on a route or as the body of a request. Manually working with the data spread out over several places is perfectly fine in some scenarios, but there are times where you want to unify that into something richer - a model - which is where Nancy’s “model binding” capabilities come into play.

> Nancy, with a single line of code, can collect information from all of the above sources, including richer request bodies such as JSON and XML, and convert them into an instance of a type of your model.

If the documentation meant that a custom Binder is needed, then ok, will make one.

**Comment by cemremengu** [comment] 2016-11-27 08:35
@codri `including richer request **bodies** such as JSON and XML`.

On a side note, why don't you send the `id` in body with XML as well ? IMHO even if you acomplished this it would just be a nasty hack. It does not sound like a good aproach at all. 

Someone looking at your XML should be able to understand the exchanged data format completely.
